name: Bug Report
description: Report a bug you've found
title: "[Bug]"
labels: "bug"
body:
-type: markdown
 attributes:
  label: what happened?
  description: Also tell us, what did you except to happen?
  placeholder: Tell us what you see!
  valodations:
    required:true
